name: Build
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal --no-modify-path -y
          # the target comes from running `rustup target list` on the Olimex board
          rustup target add armv7-unknown-linux-gnueabihf
          cargo install cross --git https://github.com/cross-rs/cross
          sudo apt-get install -y gcc-arm-linux-gnueabihf
      - name: Build
        run: cross build --target=armv7-unknown-linux-gnueabihf
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/eye
        
